version: '3.7'
services:
    postgresql:
        container_name: postgres
        image: postgres:13
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - ./data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        networks:
            - webnet
        logging:
            driver: 'json-file'
            options:
                max-size: '8m'
                max-file: '10'
        restart: always
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=postgres
            - PGADMIN_DEFAULT_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - ${ADMIN_PORT}:80
        depends_on:
            - postgres
        networks:
            - webnet
        logging:
            driver: none
        restart: always
networks:
    webnet:
        name: webnet
        driver: bridge
