version: '3.7'
services:
    postgres:
        container_name: postgres
        image: postgres:13
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - ./data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        networks:
            - webnet
        logging:
            driver: 'json-file'
            options:
                max-size: '8m'
                max-file: '10'
        restart: always
networks:
    webnet:
        name: webnet
        driver: bridge
